# Generated by Django 5.2.17 on 2026-09-30 21:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("requisitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV / Résumé"),
                            ("cover_letter", "Cover letter"),
                            ("degree", "Degree / Diploma certificate"),
                            ("transcript", "Academic transcript"),
                            ("ssce", "WAEC / NECO result"),
                            ("nysc", "NYSC certificate / exemption"),
                            ("professional", "Professional certificate"),
                            ("id", "Means of identification"),
                            ("birth", "Birth certificate / age declaration"),
                            ("lga", "Local government / state of origin letter"),
                            ("reference", "Reference / guarantor letter"),
                            ("medical", "Medical report"),
                            ("signed_offer", "Signed offer letter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("trainee", "Graduate Trainee"),
                            ("experienced", "Experienced Hire"),
                            ("contract", "Contract / Temporary"),
                            ("intern", "Intern / IT Student"),
                        ],
                        help_text="Leave empty for all hires.",
                        max_length=20,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["doc_type"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("max_marks", models.PositiveSmallIntegerField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "evaluation criteria",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=24, unique=True)),
                ("source", models.CharField(blank=True, max_length=20)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interviews"),
                            ("decision", "Evaluation & decision"),
                            ("documents", "Document review"),
                            ("offer", "Offer"),
                            ("medical", "Medicals"),
                            ("onboarding", "Onboarding"),
                            ("hired", "Hired"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("hired", "Hired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("match_grade", models.CharField(blank=True, max_length=2)),
                ("match_breakdown", models.JSONField(blank=True, default=dict)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("select", "Select"),
                            ("on_hold", "On hold"),
                            ("reject", "Reject"),
                        ],
                        max_length=10,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("status_reason", models.CharField(blank=True, max_length=255)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "stage_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("hired_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="requisitions.requisition",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "applied_at"],
                "unique_together": {("candidate", "requisition")},
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="requisitions.requisition",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="pipeline.application",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round",
                    models.CharField(
                        choices=[
                            ("technical", "Phase 1 — Technical / practical"),
                            ("behavioural", "Phase 2 — Behavioural / general"),
                            ("hod", "Phase 3 — HOD interview"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=45)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("in_person", "In person"),
                            ("video", "Video call"),
                            ("phone", "Phone call"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Room / building for in-person interviews.",
                        max_length=200,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Teams / Zoom / Meet link. Left empty, a video room is created.",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the candidate, e.g. what to bring.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "Candidate did not attend"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "candidate_response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("reschedule", "Asked to reschedule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("candidate_note", models.CharField(blank=True, max_length=500)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("invite_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="pipeline.application",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "panel",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interview_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("select", "Select"),
                            ("reject", "Reject"),
                            ("on_hold", "On hold"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="pipeline.application",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="pipeline.interview",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("application", "evaluator", "interview")},
            },
        ),
        migrations.CreateModel(
            name="MedicalCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "facility",
                    models.CharField(default="Company clinic", max_length=200),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("fit", "Fit for work"),
                            ("conditional", "Fit with conditions"),
                            ("unfit", "Not fit"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("report", models.FileField(blank=True, upload_to="medicals/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicals",
                        to="pipeline.application",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("job_title", models.CharField(max_length=150)),
                ("grade", models.CharField(blank=True, max_length=40)),
                (
                    "annual_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Annual gross salary (₦)",
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True,
                        help_text="Allowances, housing, transport, HMO, etc.",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Proposed date of joining"
                    ),
                ),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "letter",
                    models.FileField(
                        blank=True,
                        help_text="Optional signed offer letter (PDF).",
                        upload_to="offers/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent — awaiting candidate"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("review_requested", "Candidate requested review"),
                            ("superseded", "Replaced by revised offer"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "negotiation_notes",
                    models.TextField(
                        blank=True, verbose_name="Salary negotiation notes"
                    ),
                ),
                ("candidate_comment", models.TextField(blank=True)),
                (
                    "counter_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("revise", "Revise the offer"),
                            ("maintain", "Maintain current offer"),
                            ("withdraw", "Withdraw offer / move to next candidate"),
                        ],
                        max_length=10,
                    ),
                ),
                ("management_comment", models.TextField(blank=True)),
                ("management_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="pipeline.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "management_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of joining"
                    ),
                ),
                ("staff_id", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="pipeline.application",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboardings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="pipeline.onboarding",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pipeline.evaluationcriterion",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="pipeline.evaluation",
                    ),
                ),
            ],
            options={
                "ordering": ["criterion__order"],
                "unique_together": {("evaluation", "criterion")},
            },
        ),
    ]
