# Generated by Django 5.2.17 on 2026-09-30 21:52

import candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV / Résumé"),
                            ("cover_letter", "Cover letter"),
                            ("degree", "Degree / Diploma certificate"),
                            ("transcript", "Academic transcript"),
                            ("ssce", "WAEC / NECO result"),
                            ("nysc", "NYSC certificate / exemption"),
                            ("professional", "Professional certificate"),
                            ("id", "Means of identification"),
                            ("birth", "Birth certificate / age declaration"),
                            ("lga", "Local government / state of origin letter"),
                            ("reference", "Reference / guarantor letter"),
                            ("medical", "Medical report"),
                            ("signed_offer", "Signed offer letter"),
                            ("other", "Other"),
                        ],
                        default="cv",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=candidates.models.document_upload_path),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=255)),
                ("is_parsed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["doc_type", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=40)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Current location"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "highest_qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ssce", "SSCE / WAEC / NECO"),
                            ("ond", "OND / ND"),
                            ("nce", "NCE"),
                            ("hnd", "HND"),
                            ("bsc", "Bachelor's (BSc / BEng / BA / LLB)"),
                            ("pgd", "Postgraduate Diploma"),
                            ("msc", "Master's (MSc / MEng / MBA)"),
                            ("phd", "Doctorate (PhD)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Course of study"
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "degree_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "First Class / Distinction"),
                            ("2_1", "Second Class Upper / Upper Credit"),
                            ("2_2", "Second Class Lower / Lower Credit"),
                            ("third", "Third Class"),
                            ("pass", "Pass"),
                            ("na", "Not applicable"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "nysc_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Completed"),
                            ("exempted", "Exempted"),
                            ("ongoing", "Ongoing"),
                            ("not_yet", "Not yet"),
                            ("na", "Not applicable"),
                        ],
                        max_length=10,
                        verbose_name="NYSC status",
                    ),
                ),
                (
                    "years_experience",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("current_employer", models.CharField(blank=True, max_length=150)),
                ("current_job_title", models.CharField(blank=True, max_length=150)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("tools", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("education_history", models.JSONField(blank=True, default=list)),
                ("work_history", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("portal", "Online application (careers page)"),
                            ("referral", "Employee referral"),
                            ("email", "CV sent by email"),
                            ("hard_copy", "Hard copy / walk-in"),
                            ("agency", "Recruitment agency"),
                            ("internal", "Internal candidate"),
                            ("import", "Imported from spreadsheet"),
                        ],
                        default="portal",
                        max_length=20,
                    ),
                ),
                ("referral_note", models.TextField(blank=True)),
                (
                    "cv_text",
                    models.TextField(
                        blank=True,
                        help_text="Text read from the CV; used for keyword matching.",
                    ),
                ),
                (
                    "parse_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not parsed"),
                            ("ai", "AI extraction"),
                            ("heuristic", "Rule-based extraction"),
                            ("form", "Candidate form"),
                        ],
                        max_length=10,
                    ),
                ),
                ("parse_notes", models.TextField(blank=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Candidate agreed to data processing (NDPA 2023).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
