/* Fintech supervisors & programmes, imported from Fintech_Supervisors_Tracker_2027.xlsx.
 * Recruiting statements were read on the official pages (source) on 28 Sep 2026. "Not stated" = no public info found. */
window.ADMISSIONS = {
 "verifiedOn": "2026-09-28",
 "supervisors": [
  {
   "n": 1,
   "country": "Luxembourg",
   "university": "University of Luxembourg (SnT)",
   "name": "Prof. Gilbert Fridgen",
   "titleDept": "Head, FINATRAX research group; PayPal-FNR PEARL Chair in Digital Financial Services",
   "programs": "PhD in Computer Science & Computer Engineering (Information Systems specialisation)",
   "interests": "Digital financial services, fintech, blockchain/DLT, digital identities, digital euro/payments, generative AI & ML, data privacy, cybersecurity, consumer & behavioural research",
   "accepting": "YES - open 'Doctoral Researcher in Information Systems Engineering / Spontaneous Applications' posting on uni.lu (open until filled). Group says background does not matter if you like interdisciplinary work.",
   "session": "Rolling - any start date (Jan 2027 or Sept 2027 both possible)",
   "funding": "Salaried doctoral contract (UL PhD salary EUR 41,976 gross/yr, full time)",
   "contact": "Apply via uni.lu job portal. Questions: lorenzo.burcheri@uni.lu / rawan.akkouch@uni.lu. Requires a Master's degree.",
   "keyDate": "Open until filled",
   "source": "https://www.uni.lu/en/jobs/doctoral-researcher-in-information-systems-engineering-spontaneous-applications/",
   "priority": "A",
   "id": "s01",
   "emails": [
    "lorenzo.burcheri@uni.lu",
    "rawan.akkouch@uni.lu"
   ],
   "portal": true
  },
  {
   "n": 2,
   "country": "Luxembourg",
   "university": "University of Luxembourg (Department of Finance)",
   "name": "Asst. Prof. Martina Fraschini",
   "titleDept": "Assistant Professor of Finance; PI of FNR project 'Fintech and AI for Inflation Targeting' (FAIT)",
   "programs": "PhD in Finance (Year 1 = Master in Quantitative Economics & Finance, MQEF)",
   "interests": "Digital money & CBDCs, AI, fintech, innovation in banking, venture capital",
   "accepting": "DEPARTMENT RECRUITING - 'Doctoral Researcher Positions in Finance' posted on uni.lu (June 2026, open until filled). No personal call from Dr Fraschini found - email her to ask about supervision.",
   "session": "Academic-year start (programme year 1 is the MQEF) - realistic target Sept 2027; confirm",
   "funding": "Salaried doctoral contract (EUR 41,976 gross/yr)",
   "contact": "Must apply BOTH on the MQEF website AND the uni.lu job portal. Personal site: martinafraschini.com",
   "keyDate": "Open until filled",
   "source": "https://www.uni.lu/en/jobs/doctoral-researcher-positions-in-finance/",
   "priority": "A",
   "id": "s02",
   "emails": [],
   "portal": true
  },
  {
   "n": 3,
   "country": "Luxembourg",
   "university": "University of Luxembourg (Faculty of Law, Economics & Finance)",
   "name": "Prof. Dirk Andreas Zetzsche",
   "titleDept": "ADA Chair in Financial Law & Inclusive Finance",
   "programs": "Doctoral programme in Law",
   "interests": "Fintech law & regulation, digital asset funds, technology & corporate governance, inclusive finance",
   "accepting": "No current public call found - cold email.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "Email via uni.lu staff directory",
   "keyDate": "-",
   "source": "https://www.uni.lu/fdef-en/news/recognition-of-luxembourg-fintech-research-in-the-us/",
   "priority": "C",
   "id": "s03",
   "emails": []
  },
  {
   "n": 4,
   "country": "Luxembourg",
   "university": "University of Luxembourg (SnT)",
   "name": "Prof. Radu State",
   "titleDept": "Head, SEDAN research group",
   "programs": "PhD in Computer Science",
   "interests": "Blockchain, DeFi security, Ethereum front-running/MEV, big data systems, network security",
   "accepting": "No current call found (last DeFi PhD advert was 2022). Cold email.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "radu.state@uni.lu (listed in past SnT adverts)",
   "keyDate": "-",
   "source": "https://orbilu.uni.lu/profile?uid=50003137",
   "priority": "C",
   "id": "s04",
   "emails": [
    "radu.state@uni.lu"
   ]
  },
  {
   "n": 5,
   "country": "Canada",
   "university": "University of Toronto",
   "name": "Prof. Fan Long",
   "titleDept": "Associate Professor, Dept. of Computer Science",
   "programs": "MSc / PhD Computer Science",
   "interests": "Blockchain scalability, smart-contract & DeFi security (flash-loan attacks, oracle manipulation), AI for software engineering",
   "accepting": "YES - homepage states he is 'actively recruiting motivated graduate students'.",
   "session": "Sept 2027 (Fall) is the realistic target; confirm deadline on U of T CS admissions",
   "funding": "Not stated on page",
   "contact": "Read his 'Instructions to Contact Me' page first: cs.toronto.edu/~fanl/prospective-students.html",
   "keyDate": "Check U of T CS Fall 2027 deadline",
   "source": "https://www.cs.toronto.edu/~fanl/",
   "priority": "A",
   "id": "s05",
   "emails": []
  },
  {
   "n": 6,
   "country": "Canada",
   "university": "University of Toronto",
   "name": "Prof. Andreas Veneris",
   "titleDept": "Professor, Electrical & Computer Engineering (cross-appointed CS, Munk School)",
   "programs": "MASc / PhD ECE",
   "interests": "Crypto-economic incentives, mechanism design, formal methods for smart contracts, CBDCs, DeFi, techno-legal questions",
   "accepting": "No explicit statement found. His CV says all his graduate students are funded by research grants; lab is Ripple-supported (2026).",
   "session": "Not stated (Fall intake typical)",
   "funding": "Research-grant funded (per CV)",
   "contact": "veneris@eecg.toronto.edu",
   "keyDate": "-",
   "source": "https://www.ece.utoronto.ca/decentralized-technologies-andreas-veneris-ripple/",
   "priority": "B",
   "id": "s06",
   "emails": [
    "veneris@eecg.toronto.edu"
   ]
  },
  {
   "n": 7,
   "country": "Canada",
   "university": "University of Waterloo",
   "name": "Prof. Justin Wan",
   "titleDept": "Professor, School of Computer Science",
   "programs": "MMath Computational Mathematics; MMath CS; PhD CS",
   "interests": "AI/ML for computational finance ('Fintech'), option pricing, stock trading, no-arbitrage-aware ML",
   "accepting": "YES - listed as an 'open and ongoing research opportunity' on Waterloo's official research-opportunity catalogue; expressions of interest accepted for any term.",
   "session": "Any term - Jan 2027 or Sept 2027",
   "funding": "Waterloo funding for research programs; international PhDs receive IDSA tuition award",
   "contact": "Submit the Expression of Interest form on the listing (CV, average, intro). Wants calculus, linear algebra, numerical computation, ML, Python.",
   "keyDate": "Ongoing",
   "source": "https://uwaterloo.ca/future-graduate-students/catalogs/future-graduate-student-research-opportunities/fintech-artificial-intelligence-ai-machine-learning-ml",
   "priority": "A",
   "id": "s07",
   "emails": [],
   "portal": true
  },
  {
   "n": 8,
   "country": "Canada",
   "university": "Concordia University (CIISE)",
   "name": "Dr. Jeremy Clark",
   "titleDept": "Associate Professor, Concordia Institute for Information Systems Engineering",
   "programs": "MASc / PhD Information Systems Engineering",
   "interests": "Decentralized finance, zero-knowledge proofs, CBDCs, privacy, order books",
   "accepting": "MAY HAVE POSITIONS SOON - his Hiring page marks MASc and PhD as 'may have positions soon'; postdocs not hiring. PhD applicants need a crypto/security background + at least one publication; MASc is open to other backgrounds.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "Fill his application form (shared with 20+ Canadian blockchain researchers on aw3.ca) AND apply formally to Concordia. He only replies if there is a match.",
   "keyDate": "-",
   "source": "https://www.pulpspy.com/hiring.html",
   "priority": "B",
   "id": "s08",
   "emails": [],
   "webForm": true
  },
  {
   "n": 9,
   "country": "Canada",
   "university": "University of British Columbia (Okanagan)",
   "name": "Dr. Chen Feng",
   "titleDept": "Associate Professor, School of Engineering; Principal's Research Chair in Blockchain; Co-lead Blockchain@UBC",
   "programs": "MASc / PhD Engineering",
   "interests": "Blockchain consensus, incentive analysis, cross-chain exchange, rollups, TEEs, stochastic analysis of blockchains",
   "accepting": "INVITES APPLICANTS - homepage asks blockchain applicants to submit the application form (in addition to formally applying to UBCO).",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "Same aw3.ca form as Dr Clark + chen.feng@ubc.ca",
   "keyDate": "-",
   "source": "https://sites.google.com/view/chenfeng-ubc/",
   "priority": "B",
   "id": "s09",
   "emails": [
    "chen.feng@ubc.ca"
   ],
   "webForm": true
  },
  {
   "n": 10,
   "country": "Canada",
   "university": "ETS Montreal (Universite du Quebec)",
   "name": "Prof. Kaiwen Zhang",
   "titleDept": "Full Professor, Dept. of Software & IT Engineering; T-RIZE / FUSEE Lab",
   "programs": "MASc / PhD (Software & IT Engineering)",
   "interests": "Blockchain & DLT, MEV mitigation, Bitcoin/crypto forensics, DeFi governance, RWA tokenization, federated learning",
   "accepting": "YES - lab page: 'We are looking for highly motivated students'. Thesis can be written in English (classes are in French, some can be taken elsewhere).",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "Send CV + statement of research interests to Dr Kaiwen Zhang (ETS profile)",
   "keyDate": "-",
   "source": "https://fuseelab.github.io/",
   "priority": "A",
   "id": "s10",
   "emails": []
  },
  {
   "n": 11,
   "country": "Canada",
   "university": "University of Calgary",
   "name": "Dr. Sara Rouhani",
   "titleDept": "Dept. of Computer Science; TCDT Lab",
   "programs": "PhD / MSc Computer Science",
   "interests": "Blockchain & smart contracts, Layer-2 rollups, interoperability, decentralized identity, federated/split learning, agentic AI for vulnerability detection",
   "accepting": "YES - 1 FUNDED PhD + up to 2 MSc positions advertised for WINTER 2027.",
   "session": "January 2027 (Winter 2027)",
   "funding": "Funded (PhD)",
   "contact": "Email CV + short fit statement to sara.rouhani@ucalgary.ca. Needs CS degree, GPA 3.3/4.0; English waiver possible if degree taught in English. Send only one email.",
   "keyDate": "Act NOW - Winter 2027 start",
   "source": "https://tcdt.ca/open-positions",
   "priority": "A",
   "id": "s11",
   "emails": [
    "sara.rouhani@ucalgary.ca"
   ],
   "oneEmailOnly": true,
   "deadlineNote": "Act NOW: Winter (January) 2027 start",
   "urgent": true
  },
  {
   "n": 12,
   "country": "Canada",
   "university": "McGill University",
   "name": "Asst. Prof. Lili Wei",
   "titleDept": "Dept. of Electrical & Computer Engineering",
   "programs": "PhD ECE",
   "interests": "Smart-contract reliability & security (front-running detection), software analysis & testing",
   "accepting": "YES (general) - homepage: 'always looking for self-motivated PhD students'.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "Email CV + transcript (read her student advert first)",
   "keyDate": "-",
   "source": "https://liliweise.github.io/student_ad.html",
   "priority": "B",
   "id": "s12",
   "emails": []
  },
  {
   "n": 13,
   "country": "Canada",
   "university": "Concordia University (John Molson School of Business)",
   "name": "Assoc. Prof. Juliane Proelss",
   "titleDept": "Associate Professor of Finance; Jacques Menard-BMO Professor in Capital Markets",
   "programs": "MSc Finance; PhD Business Administration (Finance)",
   "interests": "Cryptocurrencies, DeFi, smart contracts, crypto momentum, investor behaviour, ESG of Bitcoin",
   "accepting": "PAST CALL - co-advertised a fully funded Finance PhD (2026/27 intake, CAD 235k+, contact before Feb 23, 2026). No 2027 call found yet - ask if it will repeat.",
   "session": "Ask about Sept 2027",
   "funding": "Past package: tuition waiver + CAD 200k scholarship + teaching income",
   "contact": "juliane.proelss@concordia.ca (needs 2-yr Master's, GPA 3.5)",
   "keyDate": "2026 deadline passed",
   "source": "https://www.concordia.ca/faculty/juliane-proelss.html",
   "priority": "B",
   "id": "s13",
   "emails": [
    "juliane.proelss@concordia.ca"
   ],
   "pastCall": true
  },
  {
   "n": 14,
   "country": "Canada",
   "university": "Concordia University (John Molson School of Business)",
   "name": "Prof. Denis Schweizer",
   "titleDept": "Finance Dept.; Desjardins Centre for Innovation and Financing",
   "programs": "PhD Business Administration (Finance)",
   "interests": "NFTs, ICOs/crypto crowdsales, crypto asset pricing, AI/ML in empirical finance",
   "accepting": "PAST CALL - co-supervisor on the same 2026/27 funded PhD advert. No 2027 call found yet.",
   "session": "Ask about Sept 2027",
   "funding": "As above",
   "contact": "denis.schweizer@concordia.ca",
   "keyDate": "2026 deadline passed",
   "source": "https://www.aw3.ca/",
   "priority": "B",
   "id": "s14",
   "emails": [
    "denis.schweizer@concordia.ca"
   ],
   "pastCall": true
  },
  {
   "n": 15,
   "country": "Canada",
   "university": "McGill University (Desautels)",
   "name": "Prof. Thomas J. Rivera",
   "titleDept": "Finance",
   "programs": "PhD in Management (Finance)",
   "interests": "DeFi, decentralized exchanges & lending, blockchain economics, PoW vs PoS",
   "accepting": "No public call found.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "thomas.rivera@mcgill.ca",
   "keyDate": "-",
   "source": "https://www.aw3.ca/",
   "priority": "C",
   "id": "s15",
   "emails": [
    "thomas.rivera@mcgill.ca"
   ]
  },
  {
   "n": 16,
   "country": "Canada",
   "university": "University of Toronto (UTM / Rotman)",
   "name": "Prof. Andreas Park",
   "titleDept": "Finance (UTM Management & Rotman); FinHub",
   "programs": "PhD (Rotman Finance)",
   "interests": "Blockchain, DeFi, automated market makers, market structure, tokenomics",
   "accepting": "No public call found.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "See andreaspark.com",
   "keyDate": "-",
   "source": "https://www.aw3.ca/",
   "priority": "C",
   "id": "s16",
   "emails": []
  },
  {
   "n": 17,
   "country": "Canada",
   "university": "York University (Schulich)",
   "name": "Prof. Henry Kim",
   "titleDept": "Schulich School of Business; blockchain.lab.yorku.ca",
   "programs": "PhD / MSc (Schulich)",
   "interests": "Enterprise blockchain, real-world-asset tokenization, payment systems, digital wallets, AI + blockchain",
   "accepting": "No public call found.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "hmkim@yorku.ca",
   "keyDate": "-",
   "source": "https://www.aw3.ca/",
   "priority": "C",
   "id": "s17",
   "emails": [
    "hmkim@yorku.ca"
   ]
  },
  {
   "n": 18,
   "country": "Canada",
   "university": "York University",
   "name": "Dr. Zissis Poulos",
   "titleDept": "School of Information Technology",
   "programs": "Graduate IT programs",
   "interests": "DeFi, declarative smart contracts, intents, order books, oracles",
   "accepting": "No public call found.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "zpoulos@yorku.ca",
   "keyDate": "-",
   "source": "https://www.aw3.ca/",
   "priority": "C",
   "id": "s18",
   "emails": [
    "zpoulos@yorku.ca"
   ]
  },
  {
   "n": 19,
   "country": "Canada",
   "university": "University of Alberta",
   "name": "Dr. Majid Khabbazian",
   "titleDept": "Electrical & Computer Engineering",
   "programs": "MSc / PhD ECE",
   "interests": "Layer-2, DeFi, zero-knowledge",
   "accepting": "No public call found.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "mkhabbazian@ualberta.ca",
   "keyDate": "-",
   "source": "https://www.aw3.ca/",
   "priority": "C",
   "id": "s19",
   "emails": [
    "mkhabbazian@ualberta.ca"
   ]
  },
  {
   "n": 20,
   "country": "Australia",
   "university": "RMIT University (Melbourne)",
   "name": "Prof. Alem Molla & Dr. Ashenafi Biru",
   "titleDept": "School of Accounting, Information Systems & Supply Chain",
   "programs": "PhD (Business Information Systems) DR201",
   "interests": "Africa's fintech entrepreneurial ecosystems - mobile money, digital payments, alternative lending (Nigeria, Kenya, SA, Ghana named)",
   "accepting": "CHECK - RMIT Centre for African Engagement PhD scholarship for citizens of African countries. Page lists 'end date of scholarship eligibility 17/11/2025', so the round may be closed - email to ask if it will be re-offered for 2027. Wants a Master's with thesis (IS/management/entrepreneurship) + mixed-methods skills.",
   "session": "2027 (RMIT has monthly intakes)",
   "funding": "Tuition for 3.5 yrs + stipend AUD 35,886/yr (2025 rate)",
   "contact": "alemayehu.molla@rmit.edu.au and ashenafi.biru@rmit.edu.au - send motivation, CV, certificates & transcripts",
   "keyDate": "Listed 17 Nov 2025 - confirm",
   "source": "https://www.rmit.edu.au/scholarships/research/the-dynamics-of-africas-fintech-entrepreneurial-ecosystems",
   "priority": "A",
   "id": "s20",
   "emails": [
    "alemayehu.molla@rmit.edu.au",
    "ashenafi.biru@rmit.edu.au"
   ],
   "pastCall": true
  },
  {
   "n": 21,
   "country": "Australia",
   "university": "RMIT University",
   "name": "Prof. Ellie Rennie (RMIT lead, ARC 'Shadow Money')",
   "titleDept": "ARC Discovery project team with Univ. of Melbourne, Swinburne, York, Amsterdam",
   "programs": "PhD",
   "interests": "Stablecoins and payment networks, tokenization, social studies of finance, blockchain studies",
   "accepting": "YES - funded PhD scholarship listed; eligibility end date 1 Jan 2028 (appears open). Needs a Master's degree.",
   "session": "2027",
   "funding": "AUD 35,886 stipend",
   "contact": "Submit CV, transcripts and a 2-page proposal with 2-3 research questions (see listing); contact Prof Rennie via RMIT directory",
   "keyDate": "Open to 1 Jan 2028",
   "source": "https://www.rmit.edu.au/scholarships/research/phd-scholarship-in-the-impacts-and-implications-of-stablecoins-on-payment-networks",
   "priority": "A",
   "id": "s21",
   "emails": [],
   "deadline": "2028-01-01",
   "deadlineNote": "Scholarship eligibility end date"
  },
  {
   "n": 22,
   "country": "Australia",
   "university": "RMIT University",
   "name": "Prof. Chris Berg",
   "titleDept": "Professor of Economics; Co-founder, RMIT Blockchain Innovation Hub",
   "programs": "Masters by Research / PhD",
   "interests": "Blockchain economics, institutional cryptoeconomics, digital-asset property rights, blockchain governance, regulation",
   "accepting": "YES - staff profile says 'Open to Masters Research or PhD student supervision'.",
   "session": "2027 (RMIT central scholarship round: commencement March 2027)",
   "funding": "Via RMIT scholarship rounds",
   "contact": "Email via RMIT profile. RMIT now REQUIRES a signed In-Principle Supervisor Supporting Statement with your application.",
   "keyDate": "RMIT 2027 intl full-application deadline: 30 Sep 2026 (EOI deadline 30 Aug 2026 already passed)",
   "source": "https://www.rmit.edu.au/contact/staff-contacts/academic-staff/b/berg-professor-chris",
   "priority": "B",
   "id": "s22",
   "emails": [],
   "deadline": "2026-09-30",
   "deadlineNote": "RMIT 2027 international full-application deadline (needs signed supervisor statement)",
   "urgent": true
  },
  {
   "n": 23,
   "country": "Australia",
   "university": "RMIT University",
   "name": "A/Prof. Xiaolu Hu",
   "titleDept": "Lead, RMIT Financial Technology & AI Cluster (Finance discipline)",
   "programs": "PhD (Finance) incl. industry-funded PhDs",
   "interests": "Machine learning in bond & equity markets, financial AI, AI security, sustainable finance, disclosure analytics",
   "accepting": "No general call; cluster runs industry-funded PhDs. Its current CSIRO iPhD (A/Prof Chao Chen, AI trading agents) is for PR/citizens only - NOT open to international applicants.",
   "session": "Not stated",
   "funding": "Industry-funded where available",
   "contact": "xiaolu.hu@rmit.edu.au",
   "keyDate": "-",
   "source": "https://fintechailab.org/",
   "priority": "C",
   "id": "s23",
   "emails": [
    "xiaolu.hu@rmit.edu.au"
   ],
   "warning": "Its current CSIRO iPhD is for Australian citizens/PR only."
  },
  {
   "n": 24,
   "country": "Australia",
   "university": "Macquarie University (+ other Digital Finance CRC universities e.g. UWA)",
   "name": "Prof. Jian Yang (contact)",
   "titleDept": "Digital Finance Cooperative Research Centre (DFCRC) Industry PhD",
   "programs": "PhD or MRes Year 2 + PhD",
   "interests": "Tokenisation, automated market makers, pricing models, CBDC, sustainable finance, blockchain security, smart-contract law & regulation",
   "accepting": "YES - Industry PhD scholarships open to DOMESTIC AND INTERNATIONAL applicants; applications 'at any time'.",
   "session": "Rolling",
   "funding": "AUD 70,000/yr for 3.5 yrs + fee offset + AUD 10k training + industry placement",
   "contact": "Apply via DFCRC website; contact jian.yang@mq.edu.au or education@dfcrc.com",
   "keyDate": "Rolling",
   "source": "https://www.mq.edu.au/research/phd-and-research-degrees/how-to-apply/scholarship-opportunities/scholarship-search/industry-phd-scholarship-digital-finance-crc",
   "priority": "A",
   "id": "s24",
   "emails": [
    "jian.yang@mq.edu.au",
    "education@dfcrc.com"
   ],
   "portal": true
  },
  {
   "n": 25,
   "country": "Australia",
   "university": "Monash University",
   "name": "Prof. Joseph Liu & Prof. Andreas Deppeler",
   "titleDept": "Co-Directors, Monash FinTech Lab (Faculty of IT / Monash Malaysia School of Business)",
   "programs": "PhD (Monash Business School, Australia or Malaysia campus)",
   "interests": "Blockchain & green finance, trusted digital transformation, inclusive fintech & digital financial literacy, ethical AI & Islamic digital finance, payments/stablecoins",
   "accepting": "YES - 'limited number of fully funded PhD scholarships' for FinTech Lab themes; application can start any time of year.",
   "session": "Rolling",
   "funding": "Fully funded (limited number)",
   "contact": "Start via Monash Business School PhD 'How to apply'; name the FinTech Lab theme",
   "keyDate": "Rolling",
   "source": "https://www.monash.edu/business/impact-labs/fintech-lab/phd-program",
   "priority": "A",
   "id": "s25",
   "emails": [],
   "portal": true
  },
  {
   "n": 26,
   "country": "Australia",
   "university": "University of Sydney",
   "name": "Dr. Angelo Aspris",
   "titleDept": "Senior Lecturer, School of Finance (Business School)",
   "programs": "PhD / MPhil Finance",
   "interests": "Market microstructure, crypto exchanges, DeFi lending, tokenisation of real-world assets",
   "accepting": "Active supervisor (4 PhDs completed) but no specific 2027 call found.",
   "session": "Not stated",
   "funding": "Via USyd scholarship rounds",
   "contact": "angelo.aspris@sydney.edu.au",
   "keyDate": "-",
   "source": "https://profiles.sydney.edu.au/angelo.aspris",
   "priority": "C",
   "id": "s26",
   "emails": [
    "angelo.aspris@sydney.edu.au"
   ]
  },
  {
   "n": 27,
   "country": "Australia",
   "university": "University of Wollongong",
   "name": "Dr. Ivy Zhou",
   "titleDept": "Senior Lecturer in Finance",
   "programs": "HDR (PhD) Finance",
   "interests": "FinTech; supervises industrial HDR students working with Australian fintech companies",
   "accepting": "Supervises industry-linked fintech HDR students (UOW page); no specific call found.",
   "session": "Not stated",
   "funding": "Not stated",
   "contact": "Via UOW staff directory",
   "keyDate": "-",
   "source": "https://www.uow.edu.au/study/fintech/",
   "priority": "C",
   "id": "s27",
   "emails": []
  },
  {
   "n": 28,
   "country": "USA",
   "university": "Worcester Polytechnic Institute (WPI)",
   "name": "Prof. Kwamie Dunbar",
   "titleDept": "Professor of Finance; Interim Dean, WPI Business School",
   "programs": "PhD in Financial Technology (FinTech) - a dedicated fintech PhD",
   "interests": "Blockchain, digital payments, AI/ML in finance, asset pricing (programme focus)",
   "accepting": "PROGRAM ADMITTING - rolling admissions; the programme allows both FALL and SPRING starts.",
   "session": "Spring (Jan) 2027 or Fall 2027",
   "funding": "Automatically considered for funding on application",
   "contact": "Apply via WPI graduate admissions; email the Business School to ask about advisors",
   "keyDate": "Business School intl deadlines: Nov 6 (Spring), June 15 (Fall)",
   "source": "https://www.wpi.edu/academics/study/financial-technology-phd",
   "priority": "A",
   "id": "s28",
   "emails": [],
   "portal": true
  },
  {
   "n": 29,
   "country": "USA",
   "university": "Yale University",
   "name": "Asst. Prof. Fan Zhang",
   "titleDept": "Dept. of Computer Science; Yale Applied Cryptography Lab",
   "programs": "PhD Computer Science",
   "interests": "zkTLS / data provenance, MEV mitigation in DeFi, blockchains + AI, trusted hardware, anonymity",
   "accepting": "YES (general) - homepage: 'I always look for motivated students and postdocs'.",
   "session": "Fall 2027 (confirm Yale CS deadline)",
   "funding": "Yale CS PhDs are funded",
   "contact": "f.zhang@yale.edu - read the 'details' link on fanzhang.me first",
   "keyDate": "Check Yale deadline (usually December)",
   "source": "https://www.fanzhang.me/",
   "priority": "B",
   "id": "s29",
   "emails": [
    "f.zhang@yale.edu"
   ]
  },
  {
   "n": 30,
   "country": "USA",
   "university": "Duke University",
   "name": "Assoc. Prof. Kartik Nayak",
   "titleDept": "Dept. of Computer Science",
   "programs": "PhD Computer Science",
   "interests": "Blockchain consensus, Ethereum PBS/MEV & decentralization, applied cryptography, sealed-bid auctions on blockchains",
   "accepting": "YES (general) - homepage: 'always looking for highly motivated Ph.D.' students.",
   "session": "Fall 2027 (confirm Duke CS deadline)",
   "funding": "Duke CS PhDs are funded",
   "contact": "kartik@cs.duke.edu",
   "keyDate": "Check Duke deadline (usually December)",
   "source": "https://users.cs.duke.edu/~kartik/",
   "priority": "B",
   "id": "s30",
   "emails": [
    "kartik@cs.duke.edu"
   ]
  },
  {
   "n": 31,
   "country": "USA",
   "university": "Columbia University",
   "name": "Assoc. Prof. Wenpin Tang",
   "titleDept": "Industrial Engineering & Operations Research (IEOR)",
   "programs": "PhD Operations Research (IEOR)",
   "interests": "ML & stochastic methods for fintech, blockchain protocol modelling, DeFi/AMMs, on-chain analytics (teaches 'Foundations of FinTech')",
   "accepting": "No personal recruiting statement found. IEOR PhD is fully funded for all admitted students.",
   "session": "Fall 2027",
   "funding": "Fully funded (tuition + stipend, 4+ yrs)",
   "contact": "Via Columbia IEOR PhD admissions",
   "keyDate": "Check IEOR deadline",
   "source": "https://ieor.columbia.edu/content/wenpin-tang",
   "priority": "C",
   "id": "s31",
   "emails": []
  },
  {
   "n": 32,
   "country": "USA",
   "university": "Cornell University",
   "name": "Prof. Will Cong",
   "titleDept": "Rudd Family Professor; Founding Director, FinTech at Cornell",
   "programs": "PhD Finance (Johnson)",
   "interests": "Tokenomics, crypto pricing, CBDCs, DeFi incentives, interpretable AI for finance",
   "accepting": "LOW PRIORITY - Cornell faculty page currently lists him as 'on leave'.",
   "session": "Fall 2027",
   "funding": "Cornell PhDs funded",
   "contact": "Via Johnson PhD admissions",
   "keyDate": "-",
   "source": "https://business.cornell.edu/profiles/lc898/",
   "priority": "C",
   "id": "s32",
   "emails": [],
   "warning": "Listed as on leave."
  }
 ],
 "keyDates": [
  {
   "when": "30 Sep 2026",
   "what": "RMIT 2027 central scholarship round - international FULL application deadline (EOI deadline of 30 Aug 2026 has passed). Commencement March 2027. A signed In-Principle Supervisor Supporting Statement is mandatory.",
   "date": "2026-09-30"
  },
  {
   "when": "Now",
   "what": "Univ. of Calgary (Dr Sara Rouhani): funded PhD + MSc positions for WINTER (January) 2027 - email immediately.",
   "date": ""
  },
  {
   "when": "6 Nov 2026",
   "what": "WPI Business School international deadline for SPRING (January) 2027 entry (June 15 for Fall).",
   "date": "2026-11-06"
  },
  {
   "when": "Rolling",
   "what": "Univ. of Luxembourg FINATRAX & Department of Finance postings (open until filled); Macquarie/DFCRC Industry PhD; Monash FinTech Lab; Waterloo (Prof. Justin Wan).",
   "date": ""
  },
  {
   "when": "Dec 2026 - Jan 2027 (typical)",
   "what": "Most US & Canadian Fall 2027 PhD deadlines fall here - confirm each department's exact date.",
   "date": "2026-12-01"
  }
 ],
 "tips": [
  "Read 2-3 of the professor's recent papers and mention one specifically in the first two lines of your email.",
  "Keep it under 200 words: who you are, your background, one research idea that fits their work, the intake you are targeting (Jan or Sept 2027), and attach CV + transcript.",
  "Follow instructions exactly where given (e.g. Dr Clark / Dr Feng use a web form; Dr Rouhani asks for one email only; Prof. Fan Long has a contact-instructions page).",
  "Canada: the aw3.ca form shares your CV with 20+ Canadian blockchain researchers at once: https://www.aw3.ca/apply.html"
 ]
};
