/*
 * The 52-week curriculum: Python -> data analysis -> stats -> ML -> advanced ML -> production.
 * Every week has checkable skills, resources, a real-world fintech problem that reuses
 * earlier weeks' skills (see `builds`), and one mentor-network task.
 */
(function () {
  const L = {
    pyTut: { t: "Python official tutorial", u: "https://docs.python.org/3/tutorial/" },
    cs50p: { t: "Harvard CS50P (free)", u: "https://cs50.harvard.edu/python/" },
    atbs: { t: "Automate the Boring Stuff (free book)", u: "https://automatetheboringstuff.com/" },
    kPy: { t: "Kaggle Learn: Python", u: "https://www.kaggle.com/learn/python" },
    realPy: { t: "Real Python tutorials", u: "https://realpython.com/" },
    gitBranch: { t: "Learn Git Branching", u: "https://learngitbranching.js.org/" },
    ghSkills: { t: "GitHub Skills", u: "https://skills.github.com/" },
    requests: { t: "requests docs", u: "https://requests.readthedocs.io/en/latest/user/quickstart/" },
    frank: { t: "Frankfurter FX API (ECB rates, free)", u: "https://www.frankfurter.app/docs/" },
    pytest: { t: "pytest: getting started", u: "https://docs.pytest.org/en/stable/getting-started.html" },
    numpy: { t: "NumPy for absolute beginners", u: "https://numpy.org/doc/stable/user/absolute_beginners.html" },
    pdIntro: { t: "pandas getting-started tutorials", u: "https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html" },
    kPandas: { t: "Kaggle Learn: pandas", u: "https://www.kaggle.com/learn/pandas" },
    pda: { t: "Python for Data Analysis, 3e (free online)", u: "https://wesmckinney.com/book/" },
    kViz: { t: "Kaggle Learn: Data Visualization", u: "https://www.kaggle.com/learn/data-visualization" },
    seaborn: { t: "seaborn tutorial", u: "https://seaborn.pydata.org/tutorial.html" },
    sqlBolt: { t: "SQLBolt (interactive)", u: "https://sqlbolt.com/" },
    kSql: { t: "Kaggle Learn: Intro to SQL", u: "https://www.kaggle.com/learn/intro-to-sql" },
    kAdvSql: { t: "Kaggle Learn: Advanced SQL", u: "https://www.kaggle.com/learn/advanced-sql" },
    modeSql: { t: "Mode SQL tutorial (window functions)", u: "https://mode.com/sql-tutorial/sql-window-functions" },
    yf: { t: "yfinance", u: "https://pypi.org/project/yfinance/" },
    fred: { t: "FRED economic data", u: "https://fred.stlouisfed.org/" },
    khanStats: { t: "Khan Academy: Statistics & Probability", u: "https://www.khanacademy.org/math/statistics-probability" },
    seeing: { t: "Seeing Theory (visual probability)", u: "https://seeing-theory.brown.edu/" },
    statquest: { t: "StatQuest (YouTube)", u: "https://www.youtube.com/@statquest" },
    evanMiller: { t: "Evan Miller A/B sample size calculator", u: "https://www.evanmiller.org/ab-testing/sample-size.html" },
    b1bLA: { t: "3Blue1Brown: Essence of Linear Algebra", u: "https://www.3blue1brown.com/topics/linear-algebra" },
    b1bCalc: { t: "3Blue1Brown: Essence of Calculus", u: "https://www.3blue1brown.com/topics/calculus" },
    mml: { t: "Mathematics for Machine Learning (free book)", u: "https://mml-book.github.io/" },
    skl: { t: "scikit-learn user guide", u: "https://scikit-learn.org/stable/user_guide.html" },
    kIntroML: { t: "Kaggle Learn: Intro to ML", u: "https://www.kaggle.com/learn/intro-to-machine-learning" },
    kInterML: { t: "Kaggle Learn: Intermediate ML", u: "https://www.kaggle.com/learn/intermediate-machine-learning" },
    kFE: { t: "Kaggle Learn: Feature Engineering", u: "https://www.kaggle.com/learn/feature-engineering" },
    ng: { t: "Andrew Ng: ML Specialization (audit free)", u: "https://www.coursera.org/specializations/machine-learning-introduction" },
    islp: { t: "ISLP: Intro to Statistical Learning (free)", u: "https://www.statlearning.com/" },
    lgbm: { t: "LightGBM docs", u: "https://lightgbm.readthedocs.io/en/stable/" },
    xgb: { t: "XGBoost docs", u: "https://xgboost.readthedocs.io/en/stable/" },
    imb: { t: "imbalanced-learn", u: "https://imbalanced-learn.org/stable/" },
    shap: { t: "SHAP docs", u: "https://shap.readthedocs.io/en/latest/" },
    fpp: { t: "Forecasting: Principles and Practice (free)", u: "https://otexts.com/fpp3/" },
    statsmodels: { t: "statsmodels time series", u: "https://www.statsmodels.org/stable/tsa.html" },
    torch: { t: "PyTorch: Learn the Basics", u: "https://pytorch.org/tutorials/beginner/basics/intro.html" },
    fastai: { t: "fast.ai Practical Deep Learning", u: "https://course.fast.ai/" },
    hf: { t: "Hugging Face LLM course", u: "https://huggingface.co/learn/llm-course" },
    nx: { t: "NetworkX tutorial", u: "https://networkx.org/documentation/stable/tutorial.html" },
    mwml: { t: "Made With ML (MLOps)", u: "https://madewithml.com/" },
    mlopsZoom: { t: "DataTalks.Club MLOps Zoomcamp", u: "https://github.com/DataTalksClub/mlops-zoomcamp" },
    fastapi: { t: "FastAPI tutorial", u: "https://fastapi.tiangolo.com/tutorial/" },
    docker: { t: "Docker: Get started", u: "https://docs.docker.com/get-started/" },
    mlflow: { t: "MLflow docs", u: "https://mlflow.org/docs/latest/index.html" },
    evidently: { t: "Evidently (drift monitoring)", u: "https://docs.evidentlyai.com/" },
    streamlit: { t: "Streamlit docs", u: "https://docs.streamlit.io/" },
    strata: { t: "StrataScratch (DS interview Qs)", u: "https://www.stratascratch.com/" },
    lcSql: { t: "LeetCode: Top SQL 50", u: "https://leetcode.com/studyplan/top-sql-50/" },
    // Datasets
    dTaiwan: { t: "Dataset: UCI Default of Credit Card Clients", u: "https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients" },
    dGMSC: { t: "Dataset: Give Me Some Credit (Kaggle)", u: "https://www.kaggle.com/c/GiveMeSomeCredit" },
    dHome: { t: "Dataset: Home Credit Default Risk (Kaggle)", u: "https://www.kaggle.com/c/home-credit-default-risk" },
    dULB: { t: "Dataset: Credit Card Fraud (ULB, Kaggle)", u: "https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud" },
    dPaySim: { t: "Dataset: PaySim mobile money (Kaggle)", u: "https://www.kaggle.com/datasets/ealaxi/paysim1" },
    dRetail: { t: "Dataset: UCI Online Retail II", u: "https://archive.ics.uci.edu/dataset/502/online+retail+ii" },
    dBankMkt: { t: "Dataset: UCI Bank Marketing", u: "https://archive.ics.uci.edu/dataset/222/bank+marketing" },
    dLending: { t: "Dataset: Lending Club loans (Kaggle)", u: "https://www.kaggle.com/datasets/wordsforthewise/lending-club" },
    dIEEE: { t: "Dataset: IEEE-CIS Fraud Detection (Kaggle)", u: "https://www.kaggle.com/c/ieee-fraud-detection" },
    dCFPB: { t: "Dataset: CFPB Consumer Complaints", u: "https://www.consumerfinance.gov/data-research/consumer-complaints/" },
    dPhrase: { t: "Dataset: Financial PhraseBank", u: "https://huggingface.co/datasets/takala/financial_phrasebank" },
    finbert: { t: "Model: FinBERT", u: "https://huggingface.co/ProsusAI/finbert" },
    dChurn: { t: "Kaggle search: bank customer churn", u: "https://www.kaggle.com/search?q=bank+customer+churn" },
  };

  const phases = [
    { id: 1, name: "Python Foundations", from: 1, to: 8, summary: "Write real programs: logic, data structures, functions, files, classes, Git and APIs." },
    { id: 2, name: "Data Analysis & SQL", from: 9, to: 16, summary: "NumPy, pandas, charts and SQL on real financial datasets. Your first public portfolio piece." },
    { id: 3, name: "Math & Statistics for ML", from: 17, to: 20, summary: "Probability, hypothesis testing, linear algebra and gradient descent, all applied to money problems." },
    { id: 4, name: "Machine Learning", from: 21, to: 32, summary: "scikit-learn, boosting, imbalance, explainability, clustering and anomaly detection. Ends with Project 1." },
    { id: 5, name: "Advanced ML", from: 33, to: 40, summary: "Time series, deep learning, NLP/LLMs and graph analytics for fraud." },
    { id: 6, name: "Production & Career", from: 41, to: 52, summary: "Testing, APIs, Docker, deployment, monitoring. Project 2, interview prep and portfolio polish." },
  ];

  const W = (n, title, skills, resources, problem, mentor) => ({ n, title, skills, resources, problem, mentor });

  const weeks = [
    // ---------------- Phase 1: Python Foundations ----------------
    W(1, "Setup & your first programs",
      ["Install Python 3.12+, VS Code and Jupyter (or use Google Colab)", "Variables, numbers, strings, booleans and type()", "print(), input() and f-strings", "Arithmetic operators, ** and round()", "Run a .py script and a notebook"],
      [L.cs50p, L.kPy, L.pyTut],
      { title: "Loan repayment calculator",
        context: "A digital lender shows every applicant their monthly repayment before they apply. Customers who see the real cost default less, so the calculator must be right to the cent.",
        data: "No dataset. Inputs typed by the user.",
        tasks: ["Ask for principal, annual interest rate (%) and term in months", "Compute the monthly payment: P·r / (1 − (1 + r)^−n), where r = annual rate / 12", "Print total repaid and total interest, formatted as currency", "Check: $10,000 at 12% for 36 months should give about $332.14 a month"],
        builds: [] },
      "Fix your LinkedIn profile: clear photo, headline like \"Aspiring Data Scientist | Python & ML for Fintech (credit risk, fraud)\", and an About section that states your 12-month mission."),

    W(2, "Decisions & loops",
      ["Comparison and logical operators", "if / elif / else", "for loops and range()", "while loops, break and continue", "Tracing code by hand to find bugs"],
      [L.cs50p, L.atbs, L.kPy],
      { title: "Amortization schedule + eligibility rules",
        context: "Before a loan officer approves anything, a rules engine applies hard policy checks, and the customer receives a month-by-month schedule of what they owe.",
        data: "Reuse your Week 1 calculator inputs.",
        tasks: ["Print a table for every month: payment, interest part, principal part, remaining balance", "Make sure the final balance reaches 0.00 (fix rounding on the last payment)", "Add eligibility rules: reject if credit score < 650 or debt-to-income ratio > 36%", "Print the exact reason for every rejection"],
        builds: [1] },
      "Read the Finder tab playbook. Follow 10 fintech company pages and 10 data scientists who post. Create free accounts on ADPList and DataTalks.Club."),

    W(3, "Lists, dictionaries, tuples & sets",
      ["Lists: indexing, slicing, append, sort", "Dictionaries: keys, values, .get(), looping with .items()", "Tuples and unpacking", "Sets for uniqueness and membership", "List and dict comprehensions"],
      [L.cs50p, L.realPy, L.pyTut],
      { title: "Transaction ledger for a neobank",
        context: "A neobank's backend receives transactions as a list of records. It must compute balances, categorise spending, and catch duplicate transaction IDs that would double-charge a customer.",
        data: "Create a list of 20 dicts: {id, account, amount, merchant, category}. Include 2 duplicate ids on purpose.",
        tasks: ["Compute each account's balance with a dict", "Total spend per category, sorted from highest to lowest", "Use a set to find duplicate transaction ids", "Reuse your Week 2 if/else logic to flag any single spend above $1,000"],
        builds: [2] },
      "Add your first 5 prospects in the Mentors tab. Turn on the bell on each profile so LinkedIn notifies you when they post. Leave your first 3 thoughtful comments."),

    W(4, "Functions, modules & errors",
      ["Defining functions, parameters, return values", "Default and keyword arguments", "Scope; importing modules (math, datetime, random)", "try / except / raise; custom exceptions", "Docstrings"],
      [L.cs50p, L.realPy],
      { title: "Payments validation service",
        context: "Payment processors reject malformed payments before they hit the ledger. A cross-border payment also carries an FX fee the customer must see up front.",
        data: "Your Week 3 transaction list.",
        tasks: ["Write validate_transaction(tx): raise ValueError for negative amounts, a missing account or an unknown currency", "Write apply_fx_fee(amount, fee_pct=1.5) and use it on non-USD payments", "Refactor your Week 2 loan calculator into monthly_payment(p, rate, months)", "Process the whole list, collecting rejected transactions and their error messages instead of crashing"],
        builds: [2, 3] },
      "Add 5 more prospects (10 total). Leave at least 5 comments this week using the comment formula in the Messages tab."),

    W(5, "Files, CSV, JSON & dates",
      ["Reading and writing text files with with open()", "The csv module (DictReader / DictWriter)", "The json module", "pathlib for file paths", "datetime: parsing, differences, formatting"],
      [L.atbs, L.realPy],
      { title: "Bank statement parser & subscription detector",
        context: "Budgeting apps turn a raw bank statement into a monthly report and warn users about subscriptions they forgot. That feature alone drives much of their user growth.",
        data: "Export a real statement from your bank as CSV with personal details removed, or generate 3 months of fake rows: date, description, amount.",
        tasks: ["Parse the CSV with DictReader and convert dates with datetime", "Build a monthly spend-by-category report and save it as JSON", "Detect recurring subscriptions: the same merchant charged about every 30 days (±3) for a similar amount", "Reuse your Week 4 validation functions to skip bad rows"],
        builds: [3, 4] },
      "Add 5 prospects (15 total). Publish your first post: what you built in Weeks 1–4 and one thing that confused you."),

    W(6, "Object-oriented programming",
      ["Classes, __init__ and attributes", "Methods and self", "Inheritance and super()", "__repr__ / __str__", "When to use a class instead of functions"],
      [L.realPy, L.pyTut],
      { title: "Model a mini bank",
        context: "Core banking systems model accounts as objects with rules. A savings account earns interest, a credit card has a limit and APR, and transfers fail safely when funds are short.",
        data: "No dataset.",
        tasks: ["Account class with deposit(), withdraw() and a history list", "SavingsAccount (monthly interest) and CreditCard (limit, APR, minimum payment = max(2% of balance, $25)) subclasses", "Bank.transfer(a, b, amount) that raises InsufficientFunds using your Week 4 custom exceptions", "Save and load all accounts to JSON (Week 5)"],
        builds: [4, 5] },
      "Engage: 5+ comments. Reply to every comment on your own post. Add 5 prospects (20 total)."),

    W(7, "Git, environments & APIs",
      ["Git: init, add, commit, push, branches", "GitHub repos and README.md", "Virtual environments (venv) and pip", "HTTP and JSON APIs with requests", "Keeping secrets out of code (.env)"],
      [L.gitBranch, L.ghSkills, L.requests, L.frank],
      { title: "Live multi-currency wallet",
        context: "Wise and Revolut hold balances in many currencies and convert at live rates. Your wallet must fetch real European Central Bank rates and never crash when the API is down.",
        data: "Frankfurter API (free, no key): ECB reference rates.",
        tasks: ["Fetch the latest EUR, USD, GBP, DKK and NGN rates with requests (use whichever currencies the API supports)", "Add convert(to_currency) to your Week 6 Account class", "Handle timeouts and bad responses with try/except (Week 4)", "Create a public GitHub repo 'fintech-ml-journey' and push Weeks 1–7 with a clean README"],
        builds: [4, 6] },
      "Pin your GitHub repo in your LinkedIn Featured section. 5+ comments. Note which prospects replied to your comments; they move to the top of your list."),

    W(8, "Consolidation: personal finance CLI + testing",
      ["Structuring a small project into modules", "Command-line menus", "Writing tests with pytest", "Reading tracebacks and debugging", "Month 2 review: redo your weakest exercise"],
      [L.pytest, L.realPy],
      { title: "Personal finance tracker (mini-project)",
        context: "Combine everything into a tool you would actually use: import a statement, categorise it, see balances in any currency, and get a subscription warning.",
        data: "Your Week 5 statement CSV.",
        tasks: ["Menu: import statement / show report / convert balance / list subscriptions", "Reuse the Week 5 parser, Week 6 classes and Week 7 FX functions", "Write at least 8 pytest tests (monthly_payment, validation, transfer failures)", "Push to GitHub with screenshots in the README"],
        builds: [5, 6, 7] },
      "Outreach begins: prospects added in Week 3 now have 30+ days of engagement. Send connection requests to the ones marked Ready (at most 5 this week). Add 5 prospects (25 total)."),

    // ---------------- Phase 2: Data Analysis & SQL ----------------
    W(9, "NumPy & vectorised thinking",
      ["Creating arrays; shape and dtype", "Indexing, slicing and boolean masks", "Vectorised math and broadcasting", "Aggregations (sum, mean, std, percentile)", "np.random for simulation"],
      [L.numpy, L.pda],
      { title: "Loan-portfolio loss simulation",
        context: "Banks hold capital against expected and unexpected losses. Expected Loss = PD × LGD × EAD (probability of default × loss given default × exposure at default).",
        data: "Simulate 5,000 loans with NumPy: amounts $1k–$50k, PD 1–15%, LGD 40–70%.",
        tasks: ["Compute expected loss per loan and for the whole portfolio in one vectorised line", "Run 10,000 Monte Carlo scenarios of which loans default", "Report the 99th-percentile loss (a simple Value-at-Risk)", "Vectorise your Week 2 amortization maths for all 5,000 loans at once and compare speed with a Python loop"],
        builds: [2, 4] },
      "Send first messages to people who accepted, using the 'After they accept' template. Keep commenting on everyone else."),

    W(10, "pandas I: DataFrames",
      ["Series and DataFrame", "read_csv / read_excel, head, info, describe", "Selecting with loc / iloc and filtering", "Sorting, new columns, value_counts", "Handling basic dtypes"],
      [L.pdIntro, L.kPandas, L.dTaiwan],
      { title: "Who defaults on credit cards?",
        context: "A Taiwanese card issuer wants to know which customer groups default most, to adjust credit limits before the next billing cycle.",
        data: "UCI Default of Credit Card Clients (30,000 customers).",
        tasks: ["Load the data and rename columns to readable names", "Default rate overall, by education, by marriage status and by age band (use pd.cut)", "Compare average credit limit (LIMIT_BAL) for defaulters and non-defaulters", "Write 3 plain-English findings as markdown in the notebook"],
        builds: [5, 9] },
      "Follow up with anyone who didn't reply after 7 days. Post: 'What 10 weeks of Python taught me about money data'. Add 5 prospects (30 total)."),

    W(11, "pandas II: cleaning, groupby & merges",
      ["Missing values: isna, fillna, dropna", "groupby with agg", "merge / join and concat", "Dates in pandas (to_datetime, .dt)", "pivot_table"],
      [L.pda, L.kPandas, L.dRetail],
      { title: "Customer value (RFM) for an e-commerce payments provider",
        context: "Payment companies such as Stripe and Adyen help merchants find their most valuable customers. RFM (recency, frequency, monetary value) is the industry's first-pass segmentation.",
        data: "UCI Online Retail II (about 1M transactions).",
        tasks: ["Clean the data: drop rows without a customer, handle returns (negative quantities and 'C' invoices)", "Compute revenue per line, then Recency, Frequency and Monetary per customer with groupby", "Score each metric into quintiles and label segments: Champions, At Risk, Lost", "Monthly revenue pivot by country; reuse your Week 10 filtering skills to find the top 5 markets"],
        builds: [10] },
      "Book your first 15-minute calls. Prepare 3 questions from the call checklist in the Messages tab."),

    W(12, "Data visualisation",
      ["matplotlib figure/axes basics", "seaborn: histplot, boxplot, barplot, heatmap", "Choosing the right chart", "Titles, labels and annotations that tell a story", "Saving charts for LinkedIn posts"],
      [L.kViz, L.seaborn, L.dGMSC],
      { title: "Credit-risk EDA report for a lending manager",
        context: "A lending manager has 10 minutes. She needs to see which borrower traits are linked to serious delinquency, not a pile of charts.",
        data: "Give Me Some Credit (150,000 borrowers).",
        tasks: ["Clean outliers in RevolvingUtilization and DebtRatio (Week 11 skills)", "Plot delinquency rate by utilisation band, age band and number of late payments", "Correlation heatmap, plus one chart you'd put on a slide", "Write 5 insights with a recommended action for each"],
        builds: [10, 11] },
      "Send thank-you notes within 24 hours of each call, with one action you'll take. Post your best credit-risk chart with 3 lines of insight."),

    W(13, "SQL I: querying",
      ["SELECT, WHERE, ORDER BY, LIMIT", "Aggregates with GROUP BY and HAVING", "INNER and LEFT JOINs", "SQLite from Python (sqlite3) and pd.read_sql", "Loading a CSV into a database"],
      [L.sqlBolt, L.kSql, L.dPaySim],
      { title: "Mobile-money fraud queries",
        context: "Fraud analysts at mobile-money operators like M-Pesa and Moniepoint live in SQL. Their first question is always: where is the fraud concentrated?",
        data: "PaySim (6.3M simulated mobile-money transactions). Take a 1M-row sample if your laptop struggles.",
        tasks: ["Load the data into SQLite with pandas (Week 11)", "Fraud rate and total fraud amount by transaction type", "Top 20 destination accounts by fraudulent amount received", "Find TRANSFERs followed by a CASH_OUT of the same amount in the same step (the classic mule pattern)"],
        builds: [10, 11] },
      "Send connection requests to the next Ready batch. Add 5 prospects (35 total)."),

    W(14, "SQL II: window functions & CTEs",
      ["Common Table Expressions (WITH)", "Subqueries", "Window functions: ROW_NUMBER, RANK, LAG, LEAD", "Running totals and moving averages with OVER()", "CASE WHEN"],
      [L.modeSql, L.kAdvSql, L.lcSql],
      { title: "Velocity rules for real-time fraud",
        context: "Card issuers block payments when a customer suddenly spends far above their normal pattern. These 'velocity rules' are written in SQL and run before any ML model.",
        data: "PaySim in SQLite (from Week 13).",
        tasks: ["Running balance per account with a window SUM", "Each account's 7-step moving average of spend", "Flag transactions more than 3× the account's trailing average", "Measure your rule: what share of flagged transactions are actually fraud (precision)? Cross-check the numbers in pandas"],
        builds: [11, 13] },
      "Follow-ups. Review your funnel: if fewer than 20% of connection requests are accepted, rewrite your connection note."),

    W(15, "Financial time data",
      ["Downloading market data with yfinance", "Returns: simple vs log", "resample and rolling windows in pandas", "Volatility, Sharpe ratio, max drawdown", "Plotting time series"],
      [L.yf, L.pda, L.fred],
      { title: "Robo-advisor portfolio analytics",
        context: "Robo-advisors such as Betterment and Scalable Capital show clients risk and return in plain numbers. Build the engine behind that dashboard.",
        data: "5 years of daily prices for 5 stocks/ETFs of your choice plus SPY (the S&P 500) via yfinance.",
        tasks: ["Daily returns and an equal-weight portfolio return series", "Annualised return, volatility and Sharpe ratio (use a 4% risk-free rate)", "Maximum drawdown and the date it happened", "Chart the portfolio against SPY and a 90-day rolling volatility; use NumPy (Week 9) for the maths"],
        builds: [9, 11, 12] },
      "5+ comments. Share your portfolio analytics chart in a post."),

    W(16, "Portfolio piece: consumer complaints analysis",
      ["Planning an analysis from a business question", "Combining SQL + pandas + charts in one notebook", "Writing an executive summary", "Clean GitHub repo structure (data/, notebooks/, README)", "Writing a LinkedIn post about your work"],
      [L.dCFPB, L.pda],
      { title: "What are US consumers complaining about in fintech?",
        context: "The US Consumer Financial Protection Bureau publishes every complaint made against financial companies. Regulators, journalists and compliance teams all mine it.",
        data: "CFPB Consumer Complaint Database (filter to the last 2 years).",
        tasks: ["Load the data into SQLite; complaints per company and product with SQL (Weeks 13–14)", "Trend of complaints for 5 fintechs vs 5 big banks, per month (Week 11 dates)", "Share of 'untimely response' by company", "Publish the notebook with a 1-page summary; post it on LinkedIn"],
        builds: [12, 13, 14] },
      "Send your complaints analysis to the prospects you've had calls with and ask them one specific question about it."),

    // ---------------- Phase 3: Math & Statistics ----------------
    W(17, "Probability & descriptive statistics",
      ["Mean, median, variance, standard deviation, percentiles", "Probability rules and conditional probability", "Bayes' theorem", "Distributions: binomial, normal, Poisson", "Simulating probability with NumPy"],
      [L.khanStats, L.seeing, L.statquest],
      { title: "Why most fraud alerts are false alarms",
        context: "A bank's fraud model catches 95% of fraud and wrongly flags only 2% of good transactions. Fraud is 0.2% of volume. Operations wants to know how many alerts are real.",
        data: "Pen and paper, then PaySim (Week 13).",
        tasks: ["Use Bayes' theorem to compute P(fraud | alert)", "Check your answer with a NumPy simulation of 1,000,000 transactions (Week 9)", "Model daily fraud-case counts as Poisson: how many analysts are needed so a day's queue is cleared 95% of the time?", "Compute the real fraud base rate in PaySim and redo the calculation"],
        builds: [9, 13] },
      "Send a monthly update to everyone you've had a call with (Monthly update template)."),

    W(18, "Inference & A/B testing",
      ["Sampling distributions and the central limit theorem", "Confidence intervals", "Hypothesis tests: t-test, chi-square, proportions z-test", "p-values, power and sample size", "Multiple-testing pitfalls"],
      [L.khanStats, L.statquest, L.evanMiller],
      { title: "Neobank onboarding A/B test + fair-lending check",
        context: "A neobank tested a shorter sign-up flow: control converted 1,120 of 10,000 visitors, variant 1,210 of 10,000. Separately, compliance wants to know whether default rates differ by sex in a card portfolio.",
        data: "The numbers above, plus UCI credit card default data (Week 10).",
        tasks: ["Two-proportion z-test and a 95% CI for the uplift. Should they ship?", "How many visitors per arm would detect a 0.5-point lift with 80% power?", "Chi-square test: is default rate independent of SEX in the Taiwan data?", "Write a short note to the product manager and one to compliance, in plain language"],
        builds: [10, 17] },
      "Next outreach batch. Add 5 prospects (40 total)."),

    W(19, "Linear algebra for ML",
      ["Vectors, matrices and their shapes", "Dot product and matrix multiplication in NumPy", "Covariance and correlation matrices", "Eigenvectors intuition and PCA", "Solving linear systems"],
      [L.b1bLA, L.mml],
      { title: "Minimum-variance portfolio & PCA of returns",
        context: "Portfolio risk is wᵀΣw: weights times the covariance matrix. Quant teams use PCA to find the hidden factors that move all stocks together.",
        data: "Your Week 15 returns.",
        tasks: ["Compute Σ and the portfolio variance wᵀΣw for equal weights", "Find minimum-variance weights with the closed form Σ⁻¹1 / (1ᵀΣ⁻¹1)", "Run PCA with NumPy (eigendecomposition); how much variance does PC1 explain?", "Compare the risk of the equal-weight and minimum-variance portfolios in a chart"],
        builds: [9, 15] },
      "Make the ask: people who were generous on calls get the 'Mentorship ask' template. Goal: first mentor by Week 20."),

    W(20, "Calculus & gradient descent",
      ["Derivatives as slopes; partial derivatives", "Loss functions (MSE)", "Gradient descent step by step", "Learning rate and convergence", "Feature scaling and why it matters"],
      [L.b1bCalc, L.ng, L.statquest],
      { title: "Credit-limit model from scratch",
        context: "Before using libraries, understand what 'training' means. Predict a customer's credit limit from their bill and payment history using only NumPy.",
        data: "UCI credit card default data (Week 10).",
        tasks: ["Pick 4 features, standardise them, and add a bias column", "Implement gradient descent for linear regression; plot loss per iteration", "Compare your weights with NumPy's least-squares solution (Week 19)", "Try 3 learning rates and explain what happens to each"],
        builds: [10, 19] },
      "Post: gradient descent explained with your credit-limit example."),

    // ---------------- Phase 4: Machine Learning ----------------
    W(21, "The ML workflow & regression",
      ["Supervised learning; train/test split", "scikit-learn fit / predict API", "LinearRegression, Ridge, Lasso", "Metrics: MAE, RMSE, R²", "Baselines: always beat 'predict the mean'"],
      [L.kIntroML, L.skl, L.islp, L.dLending],
      { title: "Pricing loans: predict the interest rate",
        context: "Marketplace lenders like Lending Club price each loan from the applicant's profile. A good pricing model means fair rates for borrowers and returns for investors.",
        data: "Lending Club loans (sample 200k rows).",
        tasks: ["Select numeric features (loan amount, annual income, DTI, FICO range, revolving utilisation)", "Mean baseline vs LinearRegression vs Ridge; report MAE in percentage points", "Compare sklearn's coefficients with your Week 20 gradient-descent version", "Plot residuals by loan grade: where does the model struggle?"],
        builds: [11, 20] },
      "Follow-ups and comments. Add 5 prospects (45 total)."),

    W(22, "Classification & business thresholds",
      ["Logistic regression", "Confusion matrix, precision, recall, F1", "ROC-AUC and PR-AUC", "Class imbalance basics", "Choosing a threshold from costs"],
      [L.skl, L.statquest, L.kIntroML, L.dGMSC],
      { title: "Approve or decline? Cost-based credit decisions",
        context: "Missing a defaulter costs about $5,000 in lost principal. Wrongly declining a good customer costs about $300 of lost interest. The best threshold is almost never 0.5.",
        data: "Give Me Some Credit (Week 12 cleaned version).",
        tasks: ["Train logistic regression; report ROC-AUC and the confusion matrix at 0.5", "Compute the total cost at every threshold from 0.01 to 0.99", "Pick the threshold that minimises cost and report the approval rate there", "Reuse your Week 12 insights to choose 2 extra engineered features and measure their impact"],
        builds: [12, 17, 21] },
      "Send a monthly update to mentors and warm contacts."),

    W(23, "Feature engineering & pipelines",
      ["One-hot and ordinal encoding", "Scaling and imputation", "ColumnTransformer + Pipeline", "Data leakage and how to avoid it", "Cross-validation"],
      [L.kFE, L.kInterML, L.skl, L.dHome],
      { title: "Home Credit: a production-style feature pipeline",
        context: "Home Credit lends to people with little credit history. Clever ratios built from application data are what make their models work.",
        data: "Home Credit Default Risk: application_train.csv.",
        tasks: ["Create ratios: credit/income, annuity/income, days employed/age, credit/goods price", "Build one Pipeline with imputation, encoding, scaling and logistic regression", "5-fold stratified cross-validated ROC-AUC", "Find and remove one leakage risk (e.g., the DAYS_EMPLOYED 365243 anomaly); explain it in the notebook"],
        builds: [11, 22] },
      "Outreach batch. Aim for 2 mentors by the end of Week 24."),

    W(24, "Decision trees & random forests",
      ["How a decision tree splits (Gini, entropy)", "Overfitting and depth control", "Bagging and random forests", "Feature importance (impurity vs permutation)", "Comparing models fairly"],
      [L.statquest, L.islp, L.skl],
      { title: "Explain a credit decision to a loan officer",
        context: "Loan officers trust a model more when they can follow its logic. A shallow tree is a readable policy; a forest is more accurate.",
        data: "Your Week 23 Home Credit pipeline.",
        tasks: ["Train a depth-3 decision tree and turn it into written 'if-then' lending rules", "Train a random forest in the same Pipeline; compare CV AUC with Week 23 logistic regression", "Permutation importance: top 10 features", "One slide: which model would you deploy and why?"],
        builds: [22, 23] },
      "Ask a mentor to review your pipeline code. A concrete, small ask is easy to say yes to."),

    W(25, "Gradient boosting & tuning",
      ["Boosting intuition", "XGBoost and LightGBM", "Hyperparameters: learning rate, depth, leaves, regularisation", "Early stopping", "Randomised search / Optuna"],
      [L.lgbm, L.xgb, L.kInterML],
      { title: "Beat the credit baseline with LightGBM",
        context: "Gradient boosting is the workhorse of credit scoring and fraud teams at most fintechs. Your job: beat the Week 23 baseline and prove it isn't luck.",
        data: "Home Credit (Weeks 23–24).",
        tasks: ["LightGBM with early stopping on a validation fold", "Tune 5 hyperparameters with randomised search; log each trial in a DataFrame", "Compare AUC with logistic regression and random forest using the same CV folds", "Apply the Week 22 cost-based threshold to your best model"],
        builds: [22, 23, 24] },
      "Post your LightGBM results: what worked, what didn't. Engage with comments."),

    W(26, "Imbalanced data & calibration",
      ["Why accuracy lies on imbalanced data", "Class weights vs SMOTE / undersampling", "PR-AUC and recall at a fixed precision", "Probability calibration (Platt, isotonic)", "Mid-year review"],
      [L.imb, L.skl, L.dULB],
      { title: "Card fraud at 0.17%",
        context: "Only 492 of 284,807 card transactions are fraud. A model that says 'never fraud' is 99.8% accurate and useless.",
        data: "ULB Credit Card Fraud dataset.",
        tasks: ["Baseline LightGBM (Week 25) vs class weights vs SMOTE, all scored with PR-AUC", "Report recall when precision is fixed at 80%", "Calibrate probabilities and plot the reliability curve", "Choose a threshold with Week 22's cost method: missed fraud = transaction amount, false alert = $5 of analyst time"],
        builds: [17, 22, 25] },
      "Mid-year review: count mentors, reply rate and calls. Adjust your country and company targeting. Send monthly updates."),

    W(27, "Explainability & fair lending",
      ["Global vs local explanations", "SHAP values and plots", "Reason codes / adverse action notices (US ECOA & Reg B)", "EU AI Act: credit scoring is 'high-risk'", "Fairness metrics: approval-rate parity, equal opportunity"],
      [L.shap, L.statquest],
      { title: "Reason codes for declined applicants",
        context: "US lenders must tell declined applicants the main reasons. The EU AI Act classifies credit scoring as high-risk, so explanations and fairness checks are mandatory in both markets.",
        data: "Your Week 25 LightGBM Home Credit model.",
        tasks: ["SHAP summary plot: which features drive risk overall?", "For 5 declined applicants, generate their top-3 reason codes in plain English", "Approval-rate gap by age group and gender at your chosen threshold", "Write a 1-page model card: purpose, data, performance, limitations, fairness"],
        builds: [18, 25] },
      "Outreach batch focused on the countries with the best reply rates. Add 5 prospects (50 total)."),

    W(28, "Unsupervised learning: clustering",
      ["K-means and choosing k (elbow, silhouette)", "Hierarchical clustering", "DBSCAN", "PCA for visualisation", "Turning clusters into business personas"],
      [L.islp, L.skl, L.statquest],
      { title: "Customer segments for a new credit card offer",
        context: "A payments company wants to launch a credit card, but only to the right merchant customers. Marketing needs personas with names, not cluster numbers.",
        data: "Your Week 11 RFM table plus extra behavioural features.",
        tasks: ["Scale features; choose k with the elbow and silhouette methods", "Profile each cluster (means, sizes) and give it a persona name", "Visualise the clusters in 2-D with PCA (Week 19)", "Recommend which segment gets the card first, with an expected-revenue estimate"],
        builds: [11, 19] },
      "Ask one mentor how credit models are validated at their company."),

    W(29, "Anomaly detection",
      ["Isolation Forest", "Local Outlier Factor", "Z-score and IQR rules", "Evaluating unsupervised models with labels", "Hybrid rules + ML systems"],
      [L.skl, L.imb],
      { title: "Hybrid fraud detection for mobile money",
        context: "New fraud patterns have no labels yet. Real systems combine hand-written rules, unsupervised anomaly scores and supervised models.",
        data: "PaySim (Weeks 13–14).",
        tasks: ["Engineer per-account features (amount vs trailing mean, balance drained to zero, etc.)", "Isolation Forest scores; check the precision of the top 1% against the real labels", "Combine your Week 14 SQL velocity rule with the anomaly score; does the combination beat either alone?", "Compare with a supervised LightGBM (Week 25) trained on the same features"],
        builds: [14, 25, 26] },
      "Follow-ups. Target: 3 mentors."),

    W(30, "PROJECT 1 (part 1): scope, data, scorecard",
      ["Writing a project brief (problem, users, success metric)", "Weight of Evidence (WoE) and Information Value (IV)", "Binning variables", "Logistic-regression scorecards (points to double the odds)", "Project repo setup"],
      [L.dHome, L.dLending, L.skl],
      { title: "Credit Risk Scoring System: brief and scorecard",
        context: "Build what a real credit-risk team ships: a traditional scorecard that regulators like, and (next week) an ML challenger model.",
        data: "Home Credit or Lending Club, your choice.",
        tasks: ["Write a 1-page brief: who uses it, what decision it drives, the success metric (e.g., expected profit)", "Bin the top 12 variables and compute WoE/IV; keep variables with IV > 0.02", "Fit a logistic scorecard and convert it to points (score 600 = 50:1 odds, 20 points to double the odds)", "Validate: AUC, KS statistic and score distribution by outcome"],
        builds: [22, 23, 27] },
      "Tell your mentors Project 1 has started and ask for feedback on your brief."),

    W(31, "PROJECT 1 (part 2): ML challenger & business case",
      ["Champion vs challenger model comparison", "Expected-profit curves", "Explaining ML to risk committees", "Stability over time (out-of-time validation)", "Model documentation"],
      [L.lgbm, L.shap],
      { title: "Credit Risk Scoring System: challenger model",
        context: "Risk committees approve a new model only if it adds profit, stays stable over time and can be explained.",
        data: "Same as Week 30.",
        tasks: ["LightGBM challenger (Week 25) vs scorecard; out-of-time validation if dates exist", "Expected-profit curve by approval rate for both models", "SHAP reason codes for the challenger (Week 27)", "Fairness check and model card"],
        builds: [25, 27, 30] },
      "Monthly update to mentors with Project 1 progress."),

    W(32, "PROJECT 1 (part 3): app & launch",
      ["Streamlit basics", "Loading a saved model (joblib)", "A simple, honest UI", "README with screenshots and results", "Launch post"],
      [L.streamlit],
      { title: "Credit Risk Scoring System: loan-officer app",
        context: "Ship it: a loan officer enters an application and sees the score, decision, top reasons and the expected profit.",
        data: "Your saved models from Weeks 30–31.",
        tasks: ["Streamlit app: input form → score, decision, top-3 reason codes", "Deploy free on Streamlit Community Cloud", "README: problem, data, approach, results, limitations, how to run", "LinkedIn launch post with a 60-second screen recording"],
        builds: [30, 31] },
      "Publish Project 1: LinkedIn post and Featured section, and send it personally to every mentor and warm contact."),

    // ---------------- Phase 5: Advanced ML ----------------
    W(33, "Time series I: classical forecasting",
      ["Trend, seasonality, stationarity", "Decomposition", "ACF / PACF", "ARIMA / SARIMA with statsmodels", "Backtesting forecasts"],
      [L.fpp, L.statsmodels, L.fred],
      { title: "Forecast consumer credit demand",
        context: "Lenders plan funding and marketing budgets from forecasts of consumer credit demand.",
        data: "FRED series TOTALSL (US consumer credit outstanding, monthly).",
        tasks: ["Plot and decompose the series; test for stationarity (ADF)", "Fit a SARIMA model; forecast 12 months with intervals", "Backtest with a rolling origin; report MAPE", "Compare against a naive 'same as last year' forecast"],
        builds: [15, 18] },
      "Outreach batch using Project 1 as your proof of value. Add 5 prospects (55 total)."),

    W(34, "Time series II: ML forecasting",
      ["Lag and rolling-window features", "Time-based cross-validation (no shuffling)", "Gradient boosting for forecasting", "Forecasting many series at once", "Holiday and calendar effects"],
      [L.fpp, L.lgbm],
      { title: "Cash-flow forecasting for small-business lending",
        context: "Revenue-based lenders such as Wayflyer lend against a merchant's future sales. Better cash-flow forecasts mean safer loans.",
        data: "Online Retail II (Week 11) aggregated to daily revenue per country.",
        tasks: ["Build lag-1/7/28 and rolling-mean features per series", "LightGBM (Week 25) with walk-forward validation", "Compare with SARIMA (Week 33) on the same horizon", "Decide how much you'd lend a merchant whose forecast P10 revenue is X"],
        builds: [11, 25, 33] },
      "Follow-ups. Target: 4 mentors."),

    W(35, "Deep learning I: neural networks",
      ["Neurons, layers and activations", "Backpropagation intuition (it's Week 20's gradient descent)", "PyTorch tensors, Dataset, DataLoader", "Training loop, loss, optimiser", "Regularisation: dropout, weight decay"],
      [L.torch, L.fastai, L.b1bCalc],
      { title: "Neural net vs gradient boosting on credit data",
        context: "Neural nets rule images and text, but on tables boosting usually wins. Find out for yourself, because interviewers ask why.",
        data: "UCI credit card default data (Week 10).",
        tasks: ["Build an MLP in PyTorch with a proper train/validation split", "Plot training vs validation loss; add early stopping", "Compare AUC with LightGBM on the same split", "Write 5 bullet points on why trees tend to win on tabular data"],
        builds: [20, 22, 25] },
      "Monthly update."),

    W(36, "Deep learning II: autoencoders & sequences",
      ["Autoencoders", "Reconstruction error for anomaly detection", "Embeddings for categorical variables", "Sequence models (RNN/LSTM/1-D CNN) overview", "GPU basics in Colab"],
      [L.torch, L.fastai],
      { title: "Autoencoder fraud detector",
        context: "Train only on normal transactions; anything the model can't reconstruct well is suspicious. This catches fraud patterns nobody has labelled yet.",
        data: "ULB Credit Card Fraud (Week 26).",
        tasks: ["Train an autoencoder on non-fraud transactions only", "Use reconstruction error as the anomaly score; PR-AUC against labels", "Compare with Isolation Forest (Week 29) and supervised LightGBM (Week 26)", "Pick a threshold with your Week 22 cost function"],
        builds: [26, 29, 35] },
      "Ask a mentor for a mock technical interview."),

    W(37, "NLP I: text classification",
      ["Text cleaning and tokenisation", "Bag-of-words and TF-IDF", "Linear models for text", "Multi-class metrics", "Error analysis"],
      [L.hf, L.skl, L.dCFPB],
      { title: "Automatic complaint routing",
        context: "Banks receive thousands of complaints a day. Routing each one to the right team automatically cuts response times and regulatory risk.",
        data: "CFPB complaints with narratives (Week 16).",
        tasks: ["Predict 'product' from the complaint narrative with TF-IDF + logistic regression", "Macro-F1 and a confusion matrix: which products get confused?", "Read 20 misrouted complaints and group the error types", "Estimate the analyst hours saved if 80% of complaints are routed automatically"],
        builds: [16, 22] },
      "Outreach batch. Add 5 prospects (60 total)."),

    W(38, "NLP II: transformers & LLMs",
      ["Transformers and embeddings (conceptually)", "Hugging Face pipelines", "Fine-tuned finance models (FinBERT)", "LLM APIs and prompt design", "Retrieval-augmented generation (RAG) basics"],
      [L.hf, L.finbert, L.dPhrase],
      { title: "Market sentiment + a fee-schedule assistant",
        context: "Investment teams score news sentiment at scale; banks deploy assistants that answer customer questions from official documents without inventing answers.",
        data: "Financial PhraseBank; your Week 15 price data; any bank's public fee-schedule PDF.",
        tasks: ["Score Financial PhraseBank with FinBERT; compare with your Week 37 TF-IDF model", "Score headlines for one stock and check correlation with next-day returns (Week 15)", "Build a small RAG: chunk the fee PDF, embed it, retrieve, answer with citations", "Test 10 questions; count hallucinations"],
        builds: [15, 37] },
      "Post your FinBERT or RAG experiment."),

    W(39, "Graph analytics for fraud rings",
      ["Graphs: nodes, edges, directed vs undirected", "NetworkX basics", "Degree, PageRank, connected components", "Fan-in / fan-out patterns", "Graph features for ML models"],
      [L.nx],
      { title: "Find money-mule networks",
        context: "Mules receive stolen money from many victims and pass it on quickly. They are much easier to see in a graph than in a table.",
        data: "PaySim (Weeks 13, 14, 29).",
        tasks: ["Build a directed graph of TRANSFERs (account → account)", "Find accounts with high fan-in followed by fast cash-out", "Connected components containing known fraud; visualise one ring", "Add graph features (in-degree, PageRank) to your Week 29 model and measure the lift"],
        builds: [13, 14, 29] },
      "Monthly update. Target: 5 mentors."),

    W(40, "Propensity & marketing ROI",
      ["Propensity modelling", "Lift and gain charts", "Campaign ROI maths", "Uplift modelling concept", "Communicating to marketing teams"],
      [L.skl, L.dBankMkt],
      { title: "Who should the bank call?",
        context: "A Portuguese bank phones customers to sell term deposits. Each call costs €5 and a sale is worth €80. Calling everyone wastes money.",
        data: "UCI Bank Marketing.",
        tasks: ["Remove the 'duration' column (it leaks the outcome; explain why)", "Propensity model with LightGBM (Week 25); gain and lift charts", "Choose how many customers to call to maximise profit", "Explain why uplift modelling would be even better"],
        builds: [22, 25, 26] },
      "Follow-ups. Ask mentors who else you should talk to (warm introductions)."),

    // ---------------- Phase 6: Production & Career ----------------
    W(41, "Software engineering for data scientists",
      ["Project layout (src/, tests/, configs)", "Type hints and docstrings", "Logging instead of print", "Config files (YAML) and CLI entry points", "Linting and formatting (ruff, black)"],
      [L.mwml, L.pytest],
      { title: "Refactor Project 1 into a package",
        context: "Notebooks don't ship. Teams expect code another engineer can install, test and run.",
        data: "Your Project 1 code.",
        tasks: ["Move logic into src/credit_risk/ modules: data, features, train, predict", "Train from the command line with a YAML config", "At least 15 pytest tests (building on Week 8)", "Add a GitHub Actions workflow that runs the tests on every push"],
        builds: [8, 32] },
      "Warm-intro outreach to people your mentors suggested."),

    W(42, "APIs & Docker",
      ["REST API concepts", "FastAPI + Pydantic validation", "Serving a model", "Docker images and containers", "Latency and load testing basics"],
      [L.fastapi, L.docker],
      { title: "Real-time transaction scoring API",
        context: "A payment has about 100 ms to be approved or blocked. The fraud model must be served behind a fast, validated API.",
        data: "Your Week 29/39 fraud model.",
        tasks: ["FastAPI /score endpoint with Pydantic validation (reject bad input, as in Week 4)", "Return the score, decision and top reasons", "Dockerise the service; run it locally", "Measure p95 latency over 1,000 requests; is it under 100 ms?"],
        builds: [4, 29, 39] },
      "Share your deployed API link with mentors."),

    W(43, "Deployment & experiment tracking",
      ["Deploying a container (Render, Railway, Hugging Face Spaces or AWS free tier)", "Environment variables and secrets", "MLflow experiment tracking", "Model registry concepts", "Reproducibility"],
      [L.mlflow, L.mlopsZoom],
      { title: "Deploy and track the fraud service",
        context: "Model risk teams ask 'which exact model is in production and how was it trained?' You must be able to answer instantly.",
        data: "Week 42 service.",
        tasks: ["Log every training run's params, metrics and artifacts to MLflow", "Register the best model and load it in the API by version", "Deploy the API publicly", "Write a runbook: how to roll back to the previous model"],
        builds: [41, 42] },
      "Monthly update."),

    W(44, "Monitoring & drift",
      ["Data drift vs concept drift", "Population Stability Index (PSI)", "Monitoring dashboards", "Alert thresholds and retraining triggers", "Champion/challenger in production"],
      [L.evidently, L.dLending],
      { title: "Is the credit model still valid?",
        context: "Applicants in 2018 look different from applicants in 2015. Credit teams watch PSI monthly: under 0.1 is stable, 0.1–0.25 needs a look, above 0.25 means act.",
        data: "Lending Club, split by issue year.",
        tasks: ["Compute PSI per feature and for the score between 2015 and 2018 applicants", "Which features drifted most? Why might that be (economy, marketing, policy)?", "Build an Evidently drift report", "Write a monitoring policy with thresholds and actions"],
        builds: [21, 31] },
      "Outreach for your remaining mentor target. Ask mentors for referrals to roles or internships."),

    W(45, "PROJECT 2 (part 1): design & features",
      ["System design for ML", "Real-time vs batch features", "Velocity and behavioural features", "Graph features", "Data contracts"],
      [L.dIEEE, L.dPaySim],
      { title: "Real-Time Fraud Detection Platform: design",
        context: "Build the flagship project fintech hiring managers love: a fraud system from raw events to a live dashboard.",
        data: "IEEE-CIS Fraud Detection (or PaySim if compute is limited).",
        tasks: ["Architecture diagram: event stream → features → model → decision → monitoring", "Velocity features from Week 14 and graph features from Week 39", "Time-based train/validation/test split", "Feature documentation table"],
        builds: [14, 39, 42] },
      "Tell mentors Project 2 has started. Ask a fraud practitioner to review your feature list."),

    W(46, "PROJECT 2 (part 2): modelling",
      ["Model selection under a latency budget", "Cost-sensitive thresholds", "Explainability for fraud analysts", "Backtesting on the time-based test set", "Error analysis"],
      [L.lgbm, L.shap, L.imb],
      { title: "Real-Time Fraud Detection Platform: model",
        context: "Fraud ops teams need high recall at a precision their analysts can handle, plus a reason for every alert.",
        data: "Week 45 features.",
        tasks: ["LightGBM + anomaly score ensemble (Weeks 26, 29, 36)", "Threshold for a budget of 200 alerts a day", "SHAP reasons per alert", "Report the dollars saved vs a rules-only baseline"],
        builds: [26, 29, 36, 45] },
      "Monthly update."),

    W(47, "PROJECT 2 (part 3): serving & monitoring",
      ["Streaming simulation", "Dashboarding", "Monitoring in production", "Load testing", "Documentation"],
      [L.fastapi, L.streamlit, L.evidently],
      { title: "Real-Time Fraud Detection Platform: live system",
        context: "Make it real: transactions stream in, get scored, and an analyst sees alerts on a dashboard.",
        data: "Your Weeks 45–46 artifacts.",
        tasks: ["Replay the test set as a stream through the Week 42 API", "Streamlit dashboard: alert queue, reasons, fraud caught, false-alert rate", "Daily PSI monitoring (Week 44)", "Docker Compose for the whole system"],
        builds: [42, 43, 44, 46] },
      "Ask a mentor to try your demo and critique it."),

    W(48, "PROJECT 2 (part 4): launch",
      ["Writing a technical case study", "Recording a demo video", "Presenting results to non-technical people", "Collecting feedback", "Portfolio integration"],
      [L.streamlit],
      { title: "Real-Time Fraud Detection Platform: case study",
        context: "The project only counts if people understand it in 2 minutes.",
        data: "Everything from Project 2.",
        tasks: ["Case study: problem, architecture, results in dollars, trade-offs, what's next", "3-minute demo video", "Polished README with architecture diagram", "Launch post; send personal notes to your mentors"],
        builds: [45, 46, 47] },
      "Publish Project 2 everywhere; send personal notes to your mentors."),

    W(49, "Interview prep: technical",
      ["SQL interview patterns (windows, self-joins, dedupe)", "Python/pandas live coding", "ML theory questions (bias-variance, regularisation, metrics)", "Explaining your projects in the STAR format", "Timed practice"],
      [L.strata, L.lcSql, L.islp],
      { title: "Case: BNPL defaults jumped from 3% to 5%",
        context: "Classic fintech interview case. The head of risk at a buy-now-pay-later company asks you to find out why defaults rose last quarter.",
        data: "Invent a realistic schema or use Lending Club as a proxy.",
        tasks: ["List hypotheses: mix shift, new merchants, a policy change, fraud, macro", "Write the SQL you'd run for each hypothesis (Week 14)", "Check for a mix shift with PSI (Week 44)", "Give a 5-minute answer out loud and record yourself"],
        builds: [14, 27, 44] },
      "Ask mentors for mock interviews or case practice."),

    W(50, "Interview prep: product & business",
      ["Metrics design (north star, guardrails)", "Experiment design (Week 18)", "Estimating business impact", "Stakeholder communication", "Behavioural questions"],
      [L.evanMiller, L.strata],
      { title: "Case: launching instant payouts",
        context: "A marketplace wants to pay sellers instantly for a 1% fee. Instant money attracts fraudsters.",
        data: "None: whiteboard it, then simulate with NumPy.",
        tasks: ["Define success and guardrail metrics", "Design the A/B test: unit, sample size, duration", "Estimate fraud exposure with a simulation (Weeks 9, 17)", "Propose the risk controls: limits, a model, holds"],
        builds: [9, 17, 18, 46] },
      "Monthly update; ask mentors how they'd approach your job search."),

    W(51, "Portfolio polish + speed sprint",
      ["Resume for DS roles (impact bullets)", "GitHub profile README", "LinkedIn Featured and About refresh", "Personal website (GitHub Pages)", "Working to a deadline"],
      [L.dChurn, L.ghSkills],
      { title: "Bonus Project 3: 5-day neobank churn sprint",
        context: "Show you can deliver fast: a retention team wants to know who will close their account next month and what to offer them.",
        data: "A Kaggle bank customer churn dataset.",
        tasks: ["Day 1–2: EDA and baseline (Weeks 12, 22)", "Day 3: LightGBM + SHAP (Weeks 25, 27)", "Day 4: retention offer policy with ROI (Week 40)", "Day 5: Streamlit demo + README (Week 32)"],
        builds: [22, 25, 27, 32, 40] },
      "Ask mentors who know your work for LinkedIn recommendations."),

    W(52, "Review & the next year",
      ["Year-in-review write-up", "Skills gap analysis", "Job/internship application plan", "Year-2 learning plan", "Thanking your network"],
      [L.mwml],
      { title: "Your fintech data science story",
        context: "Turn a year of work into a story hiring managers and mentors remember.",
        data: "Your tracker, your GitHub, your posts.",
        tasks: ["Write a year-in-review post with numbers (hours, projects, mentors)", "Update your resume with 3 quantified project bullets", "Shortlist 20 target companies from your Finder list and apply to 5", "Plan year 2: specialisation (credit risk, fraud, or quant)"],
        builds: [32, 48, 51] },
      "Send thank-you notes and your year-in-review to every mentor. Agree a year-2 check-in rhythm."),
  ];

  const projects = [
    { id: "p1", name: "Credit Risk Scoring System", weeks: "Weeks 30–32",
      summary: "Traditional WoE scorecard + LightGBM challenger, SHAP reason codes, fairness check and a deployed loan-officer app.",
      milestones: ["Project brief written", "WoE/IV scorecard built and validated", "LightGBM challenger + expected-profit curve", "Reason codes, fairness check and model card", "Streamlit app deployed", "README + launch post published", "Shared with mentors for feedback"] },
    { id: "p2", name: "Real-Time Fraud Detection Platform", weeks: "Weeks 45–48",
      summary: "Velocity + graph features, a LightGBM/anomaly ensemble, FastAPI + Docker serving, a live dashboard and drift monitoring.",
      milestones: ["Architecture diagram + feature list", "Time-based split and features built", "Model ensemble + alert-budget threshold", "FastAPI + Docker service deployed", "Streaming replay + analyst dashboard", "PSI monitoring", "Case study, demo video and launch post"] },
    { id: "p3", name: "Neobank Churn Sprint (bonus)", weeks: "Week 51",
      summary: "A 5-day end-to-end build that proves you can deliver fast.",
      milestones: ["EDA + baseline", "LightGBM + SHAP", "Retention offer policy with ROI", "Streamlit demo + README"] },
  ];

  window.CURRICULUM = { phases, weeks, projects };
})();
