# Generated by Django 5.2.17 on 2026-09-30 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("job_family", models.CharField(blank=True, max_length=60)),
                ("grade", models.CharField(blank=True, max_length=40)),
                ("description", models.TextField(blank=True)),
                ("default_min_experience", models.PositiveSmallIntegerField(default=0)),
                (
                    "default_education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ssce", "SSCE / WAEC / NECO"),
                            ("ond", "OND / ND"),
                            ("nce", "NCE"),
                            ("hnd", "HND"),
                            ("bsc", "Bachelor's (BSc / BEng / BA / LLB)"),
                            ("pgd", "Postgraduate Diploma"),
                            ("msc", "Master's (MSc / MEng / MBA)"),
                            ("phd", "Doctorate (PhD)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("default_skills", models.JSONField(blank=True, default=list)),
                ("default_tools", models.JSONField(blank=True, default=list)),
                ("default_certifications", models.JSONField(blank=True, default=list)),
                ("default_courses", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty if any department can use this role.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_roles",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Position title"),
                ),
                (
                    "positions",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Number of positions"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("new", "New position / team expansion"),
                            ("resignation", "Replacement — resignation"),
                            ("retirement", "Replacement — retirement"),
                            ("termination", "Replacement — termination / dismissal"),
                            ("transfer", "Replacement — transfer / promotion"),
                            ("temporary", "Temporary / project need"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("trainee", "Graduate Trainee"),
                            ("experienced", "Experienced Hire"),
                            ("contract", "Contract / Temporary"),
                            ("intern", "Intern / IT Student"),
                        ],
                        default="experienced",
                        max_length=20,
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=40)),
                (
                    "location",
                    models.CharField(default="Eleme, Rivers State", max_length=120),
                ),
                ("min_experience_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_experience_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("ssce", "SSCE / WAEC / NECO"),
                            ("ond", "OND / ND"),
                            ("nce", "NCE"),
                            ("hnd", "HND"),
                            ("bsc", "Bachelor's (BSc / BEng / BA / LLB)"),
                            ("pgd", "Postgraduate Diploma"),
                            ("msc", "Master's (MSc / MEng / MBA)"),
                            ("phd", "Doctorate (PhD)"),
                        ],
                        default="bsc",
                        max_length=10,
                        verbose_name="Minimum qualification",
                    ),
                ),
                (
                    "courses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Accepted courses / disciplines",
                    ),
                ),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                (
                    "preferred_skills",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Nice-to-have skills"
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Tools / software / equipment",
                    ),
                ),
                (
                    "other_requirements",
                    models.TextField(
                        blank=True,
                        help_text="E.g. NYSC completed, willingness to work shifts.",
                    ),
                ),
                ("justification", models.TextField(blank=True)),
                (
                    "job_description",
                    models.TextField(
                        blank=True, verbose_name="Job description / responsibilities"
                    ),
                ),
                (
                    "advert",
                    models.TextField(
                        blank=True,
                        help_text="Shown on the careers page.",
                        verbose_name="Public job advert",
                    ),
                ),
                ("target_start_date", models.DateField(blank=True, null=True)),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Application closing date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Awaiting HR review"),
                            ("returned", "Returned for changes"),
                            ("pending_management", "Awaiting management approval"),
                            ("approved", "Approved"),
                            ("open", "Open — accepting applications"),
                            ("on_hold", "On hold"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="core.department",
                    ),
                ),
                (
                    "hr_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions_owned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned recruiter",
                    ),
                ),
                (
                    "job_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions",
                        to="requisitions.jobrole",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacing_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requisitions",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisitionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="requisitions.requisition",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("skill", "Skill"),
                            ("tool", "Tool / Software / Equipment"),
                            ("certification", "Certification / Licence"),
                            ("course", "Course of study"),
                        ],
                        default="skill",
                        max_length=20,
                    ),
                ),
                ("job_family", models.CharField(blank=True, max_length=60)),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Other spellings, e.g. ["MS Excel", "Excel"].',
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
                "unique_together": {("name", "kind")},
            },
        ),
    ]
