# Generated by Django 5.2.17 on 2026-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="min_degree_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "First Class / Distinction"),
                    ("2_1", "Second Class Upper / Upper Credit"),
                    ("2_2", "Second Class Lower / Lower Credit"),
                    ("third", "Third Class"),
                    ("pass", "Pass"),
                ],
                max_length=10,
                verbose_name="Minimum class of degree",
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="requires_nysc",
            field=models.BooleanField(
                default=False, verbose_name="NYSC must be completed / exempted"
            ),
        ),
    ]
